name: academic_assessment_system_app
description: A local storage based academic assessment system
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # REQUIRED DEPENDENCIES
  shared_preferences: ^2.2.2
  web_socket_channel: ^3.0.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0


  

  # Flutter’s material UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/student_page.html
