// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEjRWMIYNbfGHOMsEK680_ZKdl0H8vd_c',
    appId: '1:511834213300:web:f9ae67f81e21820e03c0e1',
    messagingSenderId: '511834213300',
    projectId: 'academic-assessment-system',
    authDomain: 'academic-assessment-system.firebaseapp.com',
    databaseURL: 'https://academic-assessment-system-default-rtdb.firebaseio.com',
    storageBucket: 'academic-assessment-system.firebasestorage.app',
    measurementId: 'G-E1XV8N3LDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbaDazsJdrHb918NOqlvhAeTO4gZP1gXI',
    appId: '1:511834213300:android:0b67918bdc3c7c6d03c0e1',
    messagingSenderId: '511834213300',
    projectId: 'academic-assessment-system',
    databaseURL: 'https://academic-assessment-system-default-rtdb.firebaseio.com',
    storageBucket: 'academic-assessment-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZK3nucU6lN53bTNqMxY18oPNqvrOEcU8',
    appId: '1:511834213300:ios:483577416703cf8e03c0e1',
    messagingSenderId: '511834213300',
    projectId: 'academic-assessment-system',
    databaseURL: 'https://academic-assessment-system-default-rtdb.firebaseio.com',
    storageBucket: 'academic-assessment-system.firebasestorage.app',
    iosBundleId: 'com.example.academicAssessmentSystemApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZK3nucU6lN53bTNqMxY18oPNqvrOEcU8',
    appId: '1:511834213300:ios:483577416703cf8e03c0e1',
    messagingSenderId: '511834213300',
    projectId: 'academic-assessment-system',
    databaseURL: 'https://academic-assessment-system-default-rtdb.firebaseio.com',
    storageBucket: 'academic-assessment-system.firebasestorage.app',
    iosBundleId: 'com.example.academicAssessmentSystemApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEjRWMIYNbfGHOMsEK680_ZKdl0H8vd_c',
    appId: '1:511834213300:web:8098fbae26a178f903c0e1',
    messagingSenderId: '511834213300',
    projectId: 'academic-assessment-system',
    authDomain: 'academic-assessment-system.firebaseapp.com',
    databaseURL: 'https://academic-assessment-system-default-rtdb.firebaseio.com',
    storageBucket: 'academic-assessment-system.firebasestorage.app',
    measurementId: 'G-N0TQK9RMS8',
  );
}
